### ISSUE TITLE
Can this extension be used in standalone Siddhi Library?/ Is there any workaround method to enable http receiver?

### ISSUE THREAD

**Issue by szjiajin** [wso2-extensions/siddhi-io-http#49]
**Description:**

I noticed that it is written in Siddhi-IO-HTTP introduction

> ... This extension only works inside the WSO2 Data Analytic Server and cannot be run with standalone siddhi.

However, in the "How To Use" section below. It suggest the method of including it as a java library. I tried to include it in my siddhi project and it reported "NoSuchMethodError" in receiving http message.
(Detailed message is posted in Issues of [siddhi library)](https://github.com/wso2/siddhi/issues/807))

Does that mean if I just want to use siddhi as library then I cannot use this extension?
Is there any way I can do to establish http stream listener by using siddhi library?
Thank you in advance!

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
Siddhi - 4.1.17 
HTTP Extention - 1.0.18
**OS, DB, other environment details and versions:**    
IntelliJ IDEA 2017.3.5 (Community Edition)
Build #IC-173.4674.33, built on March 6, 2018
JRE: 1.8.0_152-release-1024-b15 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
**Steps to reproduce:**

**Related Issues:**

**Comment by szjiajin** [comment]
**Update:** This issue had a lot of progress but I am not sure which part might be useful to development/ maintaining Siddhi. Therefore I post a link to stackoverflow which describe the complete detail of my problem. Hope it could help others (although unlikely).
[https://stackoverflow.com/questions/50018296/siddhi-http-nosuchmethoderror](https://stackoverflow.com/questions/50018296/siddhi-http-nosuchmethoderror)

**Comment by suhothayan** [comment]
It is possible to run in standalone siddhi. 
Please find the details in https://stackoverflow.com/questions/50018296/siddhi-http-nosuchmethoderror
