### ISSUE TITLE
Query params are ignored from publisher.url

### ISSUE THREAD

**Issue by pranavshah029** [wso2-extensions/siddhi-io-http#75]
**Description:**

The query params placed in `publisher.url` are not been sent to the server.
Here is the code snippet
```java
@App:name("Http_trial")
@App:description("Description of the plan")

define stream SweetProductionStream (projectCode string, totalBid int );     


@sink(type="http",
        method="POST",
        headers="'Content-Type:application/json','Accept:application/json','Host:192.168.43.79'",
        follow.redirect='true',
        publisher.url = "http://192.168.43.79:8080/path?abc=xyz",
        @map(type='json', validate.json='true', @payload("""{"properties":[{"name":"amount","value":"100"}]}""")))
define stream LowProductionAlertStream (projectCode string, totalBid int);


@info(name = 'query1')
from SweetProductionStream 
select *
insert into LowProductionAlertStream;

```
Packet captured using Wireshark
![siddhiql_packet](https://user-images.githubusercontent.com/25053733/44996713-0c07f180-afc7-11e8-87e2-e66a0a8c05cf.JPG)

The request uri seen in the packet details only contains `/path` and is missing `?abc=xyz`
Is there any other way to specify query params ? Or am I missing something here ?

**Affected Product Version:**
`v1.0.33` 

**OS, DB, other environment details and versions:**    
`Windows 10` and `Ubuntu 16.04`

**Steps to reproduce:**
Use WSO2 Stream Processor Studio to create the file.
Create a http sink having query params in publisher.url

**Comment by minudika** [comment]
This is now fixed and available in the latest version. 
http://central.maven.org/maven2/org/wso2/extension/siddhi/io/http/siddhi-io-http/1.0.36/siddhi-io-http-1.0.36.jar
