### ISSUE TITLE
Host header is missing when invoking an endpoint via http-request

### ISSUE THREAD

**Issue by lasanthaS** [wso2-extensions/siddhi-io-http#82]
**Description:**
When invoking an API via `http-request` sink, `Host` HTTP header is not getting set in the HTTP request. This causes `400 Bad Request` error from the server.

This needs to be fixed to get the hostname from the URL and set into the header.

**Affected Product Version:**
1.0.39

**Comment by minudika** [comment]
Resolved, hence closing this.
