### ISSUE TITLE
File handle leak? （A large number of "pipe/eventpoll" leaks）

### ISSUE THREAD

**Issue by hnwlxywns** [wso2-extensions/siddhi-io-http#92]
**Description:**
siddhi sql like this:

@App:name("fileHandleTest")
@App:description('test')
@app:statistics(reporter = 'jmx')

define stream testStream(triggered_time long);
@sink(type='http', publisher.url='http://192.168.1.23:7031/alertCenter/merge/mergeData', method='GET',@map(type='json'))
  define stream OutputStream (triggered_time long);

@info(name = "http_data_deal_with")
from testStream#log("---------dd---------------",true)
select *
insert into OutputStream;

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
siddhi-core : <= 4.2.17
siddhi-io-http:  <=1.0.42

**OS, DB, other environment details and versions:**    
CentOS Linux release 7.5.1804 (Core)

**Steps to reproduce:**
step1: start siddhi of this siddhi-sql appliaction, 
execute cmd:
> lsof -p 7921  | wc -l
321
step2: then stop siddhi;
>lsof -p 7921  | wc -l
351
step3: start siddhi of this siddhi-sql appliaction, 
execute cmd:
> lsof -p 7921  | wc -l
381
step4: then stop siddhi;
execute cmd:
>lsof -p 7921  | wc -l
381

lsof -p <pid> 
the result: 
java    7921 root  322u  a_inode               0,10         0      6091 [eventpoll]
java    7921 root  323r     FIFO                0,9       0t0 325541144 pipe
java    7921 root  324w     FIFO                0,9       0t0 325541144 pipe
java    7921 root  325u  a_inode               0,10         0      6091 [eventpoll]
java    7921 root  326r     FIFO                0,9       0t0 325541145 pipe
java    7921 root  327w     FIFO                0,9       0t0 325541145 pipe
java    7921 root  328u  a_inode               0,10         0      6091 [eventpoll]
java    7921 root  329r     FIFO                0,9       0t0 325541146 pipe
java    7921 root  330w     FIFO                0,9       0t0 325541146 pipe
java    7921 root  331u  a_inode               0,10         0      6091 [eventpoll]
java    7921 root  332r     FIFO                0,9       0t0 325541147 pipe
java    7921 root  333w     FIFO                0,9       0t0 325541147 pipe
java    7921 root  334u  a_inode               0,10         0      6091 [eventpoll]
java    7921 root  335r     FIFO                0,9       0t0 325541148 pipe
java    7921 root  336w     FIFO                0,9       0t0 325541148 pipe
java    7921 root  337u  a_inode               0,10         0      6091 [eventpoll]
java    7921 root  338r     FIFO                0,9       0t0 325541149 pipe
java    7921 root  339w     FIFO                0,9       0t0 325541149 pipe
java    7921 root  340u  a_inode               0,10         0      6091 [eventpoll]
java    7921 root  341r     FIFO                0,9       0t0 325541150 pipe
java    7921 root  342w     FIFO                0,9       0t0 325541150 pipe
java    7921 root  343u  a_inode               0,10         0      6091 [eventpoll]

**Comment by Niveathika92** [comment]
@hnwlxywns We were also able to reproduce this. We are currently looking into the root cause of this.

**Comment by hnwlxywns** [comment]
In code : siddhi-io-http/component/src/main/java/org/wso2/extension/siddhi/io/http/sink/HttpSink.java
To resolve this bug, the code revision is as follows:

diff --git a/siddhi-io-http/component/src/main/java/org/wso2/extension/siddhi/io/http/sink/HttpSink.java b/siddhi-io-http/component/src/main/java/org/wso2/extension/siddhi/io/http/sink/HttpSink.java
index 9721f51..4bbf2cb 100644
--- a/siddhi-io-http/component/src/main/java/org/wso2/extension/siddhi/io/http/sink/HttpSink.java
+++ b/siddhi-io-http/component/src/main/java/org/wso2/extension/siddhi/io/http/sink/HttpSink.java
@@ -463,6 +463,7 @@ public class HttpSink extends Sink {
     private String bootstrapClient;
     private ConfigReader configReader;
     private SiddhiAppContext siddhiAppContext;
+    HttpWsConnectorFactory httpConnectorFactory;
 
     /**
      * Returns the list of classes which this sink can consume.
@@ -474,7 +475,7 @@ public class HttpSink extends Sink {
      */
     @Override
     public Class[] getSupportedInputEventClasses() {
-        return new Class[] {String.class, Map.class};
+        return new Class[]{String.class, Map.class};
     }
 
     /**
@@ -485,7 +486,7 @@ public class HttpSink extends Sink {
      */
     @Override
     public String[] getSupportedDynamicOptions() {
-        return new String[] {HttpConstants.HEADERS, HttpConstants.METHOD, HttpConstants.PUBLISHER_URL};
+        return new String[]{HttpConstants.HEADERS, HttpConstants.METHOD, HttpConstants.PUBLISHER_URL};
     }
 
     /**
@@ -530,7 +531,7 @@ public class HttpSink extends Sink {
         proxyHost = optionHolder.validateAndGetStaticValue(HttpConstants.PROXY_HOST, EMPTY_STRING);
         proxyPort = optionHolder.validateAndGetStaticValue(HttpConstants.PROXY_PORT, EMPTY_STRING);
         proxyUsername = optionHolder.validateAndGetStaticValue(HttpConstants.PROXY_USERNAME,
-                 EMPTY_STRING);
+                EMPTY_STRING);
         proxyPassword = optionHolder.validateAndGetStaticValue(HttpConstants.PROXY_PASSWORD,
                 EMPTY_STRING);
         clientBootstrapConfiguration = optionHolder
@@ -622,6 +623,16 @@ public class HttpSink extends Sink {
             clientConnector = null;
             log.info("Server connector for url " + publisherURL + " disconnected.");
         }
+
+        if (this.httpConnectorFactory != null) {
+            try {
+                this.httpConnectorFactory.shutdown();
+                this.httpConnectorFactory = null;
+            } catch (InterruptedException e) {
+                ;
+            }
+
+        }
     }
 
     /**
@@ -764,6 +775,7 @@ public class HttpSink extends Sink {
         } else {
             httpConnectorFactory = new DefaultHttpWsConnectorFactory();
         }
+        this.httpConnectorFactory = httpConnectorFactory;
 
         //if proxy username and password not equal to null then create proxy configurations
         if (!EMPTY_STRING.equals(proxyHost) && !EMPTY_STRING.equals(proxyPort)) {

**Comment by Niveathika92** [comment]
@hnwlxywns, Thank you for your contribution. We have identified the same issue in the http-source and fixing it at the same time.

**Comment by alexandrejuma** [comment]
Can also confirm that with kafka source connector the same happens. I'm currently developing with WSO2 Stream Processor Studio and I recurrently have to restart it due to Max Open File exceptions on my Siddhi Application console.

Freshly started application:

root@RHTPINEC024:~# lsof -p 3360 | egrep "pipe|eventpoll"  | awk '{print $NF}' | sort | uniq -c
   1159 [eventpoll]
   2318 pipe

Also, I'm not sure how linux limits are accounted for, but if you look at the thread level (by default it appears to start 200 threads), you get a lot of file descriptions open:

root@RHTPINEC024:~# lsof | grep 3360 | egrep "pipe|eventpoll"  | awk '{print $NF}' | sort | uniq -c
 236597 [eventpoll]
 473194 pipe
